---
title: "Assignment 1"
---

My first assignment has three parts.

## (a)

[R vs Python](https://www.youtube.com/watch?v=4lcwTGA7MZw) This the video I have chosen.

### Brief Summary:

## (b)

``` {r}
# R program to add two numbers
numb1 <- 8
numb2 <- 4

# Adding two numbers 
sum <- numb1 + numb2 

print(paste("The sum is", sum))
```

``` python
# Python program to add two numbers

numb1 = 8
numb2 = 4

# Adding two numbers 
sum = numb1 + numb2 

# Printing the result 
print("The sum is", sum) 
```

``` {r}
#Create a vector:
my_vec <- c(1, 2, 3, 4, 5, 6, 7, 8)
print(my_vec[seq(2, length(my_vec), 3)])
```

``` python
#Create a list:
my_vec = [1, 2, 3, 4, 5, 6, 7, 8]
print(my_vec[1::3])
```

``` {r}
#Define a function:
my_sum <- function(x, y){
  x <- x + 1
  y <- y + 1
  return(x + y)
}
#Test the function
print(my_sum(1, 2))
```

``` python
#Define a function:
def my_sum(x, y):
  x = x + 1
  y = y + 1
  return x + y
#
#Test the function
print(my_sum(1, 2))
```

## (c)

```{r}
library(dslabs)
data("na_example")
na_example
# Total number of NAs in the data frame:
sum(is.na(na_example))
no_na <- ifelse(is.na(na_example), 0, na_example)
no_na
# Total number of NAs in the new data frame:
sum(is.na(no_na))
```
